CREATE TABLE IF NOT EXISTS bet_results (
    bet_result_id INT PRIMARY KEY AUTO_INCREMENT,
    player_id VARCHAR(50) NOT NULL,
    token VARCHAR(50) NOT NULL,
    match_id VARCHAR(50) NOT NULL,
    room_id VARCHAR(50),
    transaction_id VARCHAR(255),
    game_settings_id INT,
    round_no INT NOT NULL,
    bet_amt INT NOT NULL,
    won_amt INT NOT NULL,
    status ENUM('WIN', 'LOSS', 'CASHOUT') DEFAULT 'LOSS',
    reels JSON,
    result JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (game_settings_id) REFERENCES game_settings(game_settings_id)
);

CREATE TABLE IF NOT EXISTS transactions (
    ttn_id INT PRIMARY KEY AUTO_INCREMENT,
    bet_result_id INT,
    player_id VARCHAR(150) NOT NULL,
    token VARCHAR(150) NOT NULL,
    amount INT NOT NULL,
    room_id VARCHAR(150) NOT NULL,
    txn_id VARCHAR(150) NOT NULL,
    type ENUM('CREDIT', 'DEBIT', 'ROLLBACK') NOT NULL,
    operator_id VARCHAR(50) NOT NULL,
    txn_ref_id VARCHAR(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (bet_result_id) REFERENCES bet_results (bet_result_id)
);

create table if not exists game_settings (
    game_settings_id int primary key auto_increment,
    game_name varchar(50),
    max_bet int not null,
    min_bet int not null,
    join_amt int,
    game_type enum('SINGLE_PLAYER', 'MULTI_PLAYER'),
    min_player int,
    max_player int,
    winning_combinations json not null,
    payouts json not null,
    payline_index json not null,
    payNames json not null,
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp on update current_timestamp
);

/* load congig */
INSERT INTO
    game_settings (
        game_name,
        max_bet,
        min_bet,
        join_amt,
        game_type,
        min_player,
        max_player,
        winning_combinations,
        payouts,
        payline_index,
        payNames
    )
VALUES
    (
        'slot_machine',
        20000,
        10,
        11,
        'SINGLE_PLAYER',
        1,
        1,
        JSON_OBJECT(
            'winningCombinations3Match',
            JSON_ARRAY(
                JSON_ARRAY(0, 1, 2),
                JSON_ARRAY(1, 2, 3),
                JSON_ARRAY(2, 3, 4),
                JSON_ARRAY(5, 6, 7),
                JSON_ARRAY(6, 7, 8),
                JSON_ARRAY(7, 8, 9),
                JSON_ARRAY(10, 11, 12),
                JSON_ARRAY(11, 12, 13),
                JSON_ARRAY(12, 13, 14),
                JSON_ARRAY(0, 6, 12),
                JSON_ARRAY(2, 6, 10),
                JSON_ARRAY(2, 8, 14),
                JSON_ARRAY(4, 8, 12),
                JSON_ARRAY(5, 11, 12),
                JSON_ARRAY(12, 13, 9),
                JSON_ARRAY(0, 1, 7),
                JSON_ARRAY(3, 4, 7),
                JSON_ARRAY(7, 10, 11),
                JSON_ARRAY(7, 13, 14),
                JSON_ARRAY(5, 1, 2),
                JSON_ARRAY(2, 3, 9),
                JSON_ARRAY(5, 1, 7)
            ),
            'winningCombinations4Match',
            JSON_ARRAY(
                JSON_ARRAY(0, 1, 2, 3),
                JSON_ARRAY(1, 2, 3, 4),
                JSON_ARRAY(5, 6, 7, 8),
                JSON_ARRAY(6, 7, 8, 9),
                JSON_ARRAY(10, 11, 12, 13),
                JSON_ARRAY(11, 12, 13, 14),
                JSON_ARRAY(0, 6, 8, 12),
                JSON_ARRAY(4, 6, 8, 12),
                JSON_ARRAY(6, 7, 8, 9),
                JSON_ARRAY(0, 1, 3, 7),
                JSON_ARRAY(1, 3, 4, 7),
                JSON_ARRAY(7, 10, 11, 13),
                JSON_ARRAY(7, 11, 13, 14),
                JSON_ARRAY(9, 11, 12, 13),
                JSON_ARRAY(1, 2, 5, 3),
                JSON_ARRAY(1, 2, 3, 9),
                JSON_ARRAY(1, 3, 5, 7),
                JSON_ARRAY(1, 2, 7, 9)
            ),
            'winningCombinations5Match',
            JSON_ARRAY(
                JSON_ARRAY(0, 1, 2, 3, 4),
                JSON_ARRAY(5, 6, 7, 8, 9),
                JSON_ARRAY(10, 11, 12, 13, 14),
                JSON_ARRAY(0, 4, 6, 8, 12),
                JSON_ARRAY(2, 6, 8, 11, 14),
                JSON_ARRAY(0, 1, 3, 4, 7),
                JSON_ARRAY(7, 10, 11, 13, 14),
                JSON_ARRAY(5, 9, 11, 12, 13),
                JSON_ARRAY(1, 2, 3, 5, 9),
                JSON_ARRAY(1, 3, 5, 7, 9)
            )
        ),
        JSON_OBJECT(
            'APPLE',
            JSON_OBJECT('FIVE', 6.8, 'FOUR', 4.9, 'THREE', 2.4),
            'GRAPE',
            JSON_OBJECT('FIVE', 19.5, 'FOUR', 9.8, 'THREE', 4.9),
            'LEMON',
            JSON_OBJECT('FIVE', 4.8, 'FOUR', 2.9, 'THREE', 2.4),
            'CHERRY',
            JSON_OBJECT('FIVE', 2.9, 'FOUR', 1.9, 'THREE', 1.4),
            'ORANGE',
            JSON_OBJECT('FIVE', 1.9, 'FOUR', 0.9, 'THREE', 0.4),
            'BLUEBERRY',
            JSON_OBJECT('FIVE', 9.8, 'FOUR', 6.9, 'THREE', 2.9),
            'STRAWBERRY',
            JSON_OBJECT('FIVE', 34.5, 'FOUR', 14.8, 'THREE', 9.8)
        ),
        JSON_OBJECT(
            '0',
            JSON_ARRAY(0, 1, 2, 3, 4),
            '1',
            JSON_ARRAY(5, 6, 7, 8, 9),
            '2',
            JSON_ARRAY(10, 11, 12, 13, 14),
            '3',
            JSON_ARRAY(0, 6, 12, 8, 4),
            '4',
            JSON_ARRAY(10, 6, 2, 8, 14),
            '5',
            JSON_ARRAY(0, 1, 7, 3, 4),
            '6',
            JSON_ARRAY(10, 11, 7, 13, 14),
            '7',
            JSON_ARRAY(5, 11, 12, 13, 9),
            '8',
            JSON_ARRAY(5, 1, 2, 3, 9),
            '9',
            JSON_ARRAY(5, 1, 7, 3, 9)
        ),
        JSON_OBJECT(
            '0',
            'STRAWBERRY',
            '1',
            'GRAPE',
            '2',
            'BLUEBERRY',
            '3',
            'APPLE',
            '4',
            'LEMON',
            '5',
            'CHERRY',
            '6',
            'ORANGE'
        )
    );